options:
    formatter: stylish
files:
    include: '**/*.s+(a|c)ss'
rules:
    indentation:
        - 1
        -
            size: 4

    nesting-depth: 0
    no-css-comments: 0
    no-color-literals: 0
    no-color-keywords: 0
    property-sort-order: 0
    hex-notation: 0
    no-ids: 0
    no-important: 0
    force-pseudo-nesting: 0
